name: Switch workflow branches
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to check"
        required: false

env:
  NEXT_TAG: ${{ github.event.inputs.version }}

jobs:
  branch-switch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: '/tmp/gitpod/'
          repository: 'gitpod-io/gitpod'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Run the branch switch-a-roo
        run: node utils/switchBranch.js
      - name: Create Pull Request (openvscode-releases)
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update release branch"
          branch: "update-branches"
          delete-branch: true
          title: "Update workflow branches"
      - name: Create Pull Request (gitpod)
        uses: peter-evans/create-pull-request@v4
        with:
          path: /tmp/gitpod/
          commit-message: "code: Update Nightly"
          branch: "code-update-nightly"
          delete-branch: true
          title: "code: Update Nightly"
